# Generated by Django 4.1.4 on 2023-08-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_game_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
