# Generated by Django 4.2.4 on 2023-08-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_remove_review_game_delete_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_blind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_curtain',
            field=models.BooleanField(default=False),
        ),
    ]
